In [24]:
import numpy as np


np.random.seed(0)
x0 = np.random.rand(5)
x1 = np.random.rand(5)

y = np.random.rand(5)

x0, x1, y

(array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ]),
 array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152]),
 array([0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606]))

In [42]:
x = np.stack([x0, x1], axis=1)
x

array([[0.5488135 , 0.64589411],
       [0.71518937, 0.43758721],
       [0.60276338, 0.891773  ],
       [0.54488318, 0.96366276],
       [0.4236548 , 0.38344152]])

In [44]:
res = np.dot(x.T, y)

# 手动计算验证
manual_res = np.array([
    np.sum(x0 * y),  # x0与y的点积
    np.sum(x1 * y)   # x1与y的点积
])

print("x.T:\n", x.T)
print("\ny:", y)
print("\nNumPy 计算结果:", res)
print("手动计算结果:", manual_res)
print("结果是否一致:", np.allclose(res, manual_res))

x.T:
 [[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]]

y: [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]

NumPy 计算结果: [1.68960268 2.16857618]
手动计算结果: [1.68960268 2.16857618]
结果是否一致: True


In [8]:
from test_data_set.test_data_gen import linear_data

x, y = linear_data()

x.shape

(1000, 2)